employee_id=int(input("enter int type employee_id: "))
name=input("enter name: ")
hourly_rate=float(input("enter float type hourly_rate: "))
is_active=bool(input("enter bool type value is_active: "))
print(type(employee_id),employee_id)
print(type(name), name)
print(type(hourly_rate), hourly_rate)
print(type(is_active), is_active)
print("After converting hourly_rate to an integer", int(hourly_rate))
